### ISSUE TITLE
is it possible to add feature in shell script to detect what is the id of battery?

### ISSUE THREAD

**Issue by alphaprads** [Deerrorer/dotfiles3#11]
this id would be used while configuring polybar to give it correct arguements making it simpler to install 
if yes i'm ready to work on this.
similarly we could do for all parts of system that require user inputs to conifgure

**Comment by Keyitdev** [comment]
I think it is possible, but it is very messy. 

- if you use a computer, you do not have a battery
- some laptops use 2 and more batteries
- same with monitors, you can have 1, 2 or even 10, the names of the monitors vary depending on the type of plug-in, and many other things
- and again with the networking, many network interfaces exists, dhcpd, network daemons, and much more

All this, complicates the process of obtaining such information.
Besides, the user may just not want to have a polybar on the second screen. That's why I didn't automate this process.

So if you want, you can try but in my opinion it is too much work, too little effect.

**Comment by alphaprads** [comment]
oh okay i'll try making the program for that i hope it doesn't unnecessarily complicate the install process
