### ISSUE TITLE
unable to change colours on i3lock 

### ISSUE THREAD

**Issue by rustedusted** [Deerrorer/dotfiles3#18]
i edited the lock command in bin to 
`#!/bin/sh

font="dedede"
green="9ece6a"
red="db4b4b"

i3lock --color 000000
`

but when my laptop goes to sleep automatically i don't see the black colour that i have put in the command when i do Mod+i i see black screen which i love to use btw

also nice configs man

which file contains the execution of lock screen on sleep 

and also is it possible to change sleep time

**Comment by Keyitdev** [comment]
Hi,
### Enable auto lock on sleep 
You need to install `xss-lock`.
```yay -S xss-lock```
And enable it (put this in i3 config instead of this line).
https://github.com/Keyitdev/dotfiles/blob/fa1bbd450250bb7364da9449f3834a3575dd9688/config/i3/config#L33
`exec --no-startup-id xss-lock --transfer-sleep-lock -- lock --nofork`
And **REBOOT**.

### Change sleep time
If you want to change sleep time, you can use `xset`.
https://wiki.archlinux.org/title/Display_Power_Management_Signaling#Configuration
 https://wiki.archlinux.org/title/Session_lock#xss-lock
Use `xset q` to check current settings.
```
Screen Saver:
  prefer blanking:  yes    allow exposures:  yes
  timeout:  600    cycle:  600
DPMS (Display Power Management Signaling):
  Standby: 600    Suspend: 600    Off: 600
  DPMS is Enabled
  Monitor is On
  ```
And use `xset s 180 120` or `xset dpms 10 10 10` to change it.
All these changes are runtime, so if you want to save them, you have to put them in the i3 configuration or edit some configs in systemd.

```
/etc/X11/xorg.conf.d/10-serverflags.conf

Section "ServerFlags"
    Option "StandbyTime" "10"
    Option "SuspendTime" "20"
    Option "OffTime" "30"
EndSection

```
[More info](https://wiki.archlinux.org/title/Display_Power_Management_Signaling#Configuration)

I hope this helps, but in my personal experience `xss` and `dpms` don't always work as intended. So you may want to check out alternatives such as `xautolock` or something similar.

**Comment by rustedusted** [comment]
oh okay got it thanks will try that
